name: dtgym
channels:
- pytorch
dependencies:
- python=3.8.5
- anaconda
- pytorch=1.10.2
- cudatoolkit=11.3
- numpy
- pip
- pip:
  - gym==0.18.3
  - d4rl==1.1
  - mujoco-py==2.1.2.14
  - numpy==1.20.3
  - torch==1.10.2
  - transformers==4.5.1
  - wandb==0.9.1
  - pandas=1.4.1
  - h5py=2.10.0
  - pytorch-metric-learning==1.3.0
  - ray==1.12.0
  - tensorboardx==2.5
